
INSERT INTO t_agence (AGC_ID_N,AGC_RAISONSOCIALE_C,AGC_ADRESSE1_C,AGC_ADRESSE2_C,AGC_CODEPOSTAL_C,AGC_VILLE_C,AGC_TELEPHONE_C,AGC_FAX_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (1, 'Wyniwyg Rhônes Alpes', NULL, NULL, NULL, 'Lyon', NULL, NULL, 'gestcv.sourceforge.net', '2006-01-03-00.00.00', NULL, NULL);
INSERT INTO t_agence (AGC_ID_N,AGC_RAISONSOCIALE_C,AGC_ADRESSE1_C,AGC_ADRESSE2_C,AGC_CODEPOSTAL_C,AGC_VILLE_C,AGC_TELEPHONE_C,AGC_FAX_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (2, 'Wyniwyg Atlantique', NULL, NULL, NULL, 'Nantes', NULL, NULL, 'gestcv.sourceforge.net', '2006-01-03-00.00.00', NULL, NULL);
INSERT INTO t_agence (AGC_ID_N,AGC_RAISONSOCIALE_C,AGC_ADRESSE1_C,AGC_ADRESSE2_C,AGC_CODEPOSTAL_C,AGC_VILLE_C,AGC_TELEPHONE_C,AGC_FAX_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION)  VALUES (3, 'Wyniwyg Ile de France', '57/63, rue Ernest Renan', NULL, '92000', 'Nanterre', NULL, NULL, 'gestcv.sourceforge.net', '2006-01-03-00.00.00', NULL, NULL);
INSERT INTO t_agence (AGC_ID_N,AGC_RAISONSOCIALE_C,AGC_ADRESSE1_C,AGC_ADRESSE2_C,AGC_CODEPOSTAL_C,AGC_VILLE_C,AGC_TELEPHONE_C,AGC_FAX_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION)  VALUES (4, 'Wyniwyg Normandie', NULL, NULL, NULL, 'Mont St Aignan', NULL, NULL, 'gestcv.sourceforge.net', '2006-01-03-00.00.00', NULL, NULL);
INSERT INTO t_agence (AGC_ID_N,AGC_RAISONSOCIALE_C,AGC_ADRESSE1_C,AGC_ADRESSE2_C,AGC_CODEPOSTAL_C,AGC_VILLE_C,AGC_TELEPHONE_C,AGC_FAX_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION)  VALUES (5, 'Wyniwyg S.A.S.', '1, rue Jean Monnet', NULL, '94736', 'Nogent sur Marne cedex', NULL, NULL, 'gestcv.sourceforge.net', '2006-01-03-00.00.00', NULL, NULL);

INSERT INTO t_tablereference (TRF_ID_N,TRF_TYPE_C,TRF_VALEUR_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (1,'SITUATION_FAMILIALE','Célibataire','gestcv.sourceforge.net','2006-01-14-00.00.00',null,null);
INSERT INTO t_tablereference (TRF_ID_N,TRF_TYPE_C,TRF_VALEUR_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (2,'SITUATION_FAMILIALE','Marié','gestcv.sourceforge.net','2006-01-14-00.00.00',null,null);




INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (1,'ZERR','Angelo','1977-02-24-00.00.00','Wissembourg',1,'angelo.zerr@gmail.com','2001-09-11-00.00.00',1,'Ingénieur Nouvelles Technologies',1,'gestcv.sourceforge.net','2006-01-04-00.00.00','','2009-09-08-00.00.00');
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (2,'RAYMOND','Nicolas',null,'',1,'',null,1,'',1,'gestcv.sourceforge.net','2006-01-04-00.00.00','a','2006-04-28-00.00.00');
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (3,'ARQUES','Christianne',null,'',1,'',null,1,'',2,'gestcv.sourceforge.net','2006-01-11-00.00.00','a','2006-05-10-00.00.00');
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (4,'GAMET','Olivier',null,'',1,'',null,1,'',2,'gestcv.sourceforge.net','2006-01-11-00.00.00','a','2006-02-10-00.00.00');
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (5,'MAILLOT','Alexis',null,'',0,'',null,5,'',null,'gestcv.sourceforge.net','2006-01-13-00.00.00','a','2006-02-22-00.00.00');
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (6,'BOUCHET','Nicolas',null,'',0,'',null,5,'',null,'gestcv.sourceforge.net','2006-02-22-00.00.00',null,null);
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (7,'CHARRON','Philipe',null,'',0,'',null,2,'',null,'a','2006-02-22-00.00.00',null,null);
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (8,'MERLE','Alexis',null,'',0,'',null,2,'',null,'a','2006-02-22-00.00.00',null,null);
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (11,'p','p',null,'',0,'',null,2,'',null,'a','2006-05-10-00.00.00',null,null);
INSERT INTO t_collaborateur (COL_ID_N,COL_NOM_C,COL_PRENOM_C,COL_DATENAISSANCE_D,COL_LIEUNAISSANCE_C,COL_PERMISB_B,COL_EMAIL_C,COL_DATE_DEBUTCARRIERE_D,COL_ID_AGENCE_N,COL_TITRE_C,COL_ID_SITUATION_FAMILIALE_N,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (12,'b','b','2005-01-01-00.00.00','',0,'',null,2,'',null,'a','2006-05-10-00.00.00',null,null);




INSERT INTO t_domaine (DOM_ID_N,DOM_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (1,'Langages','wwra@wyniwyg.fr','2006-01-10-00.00.00',null,null);
INSERT INTO t_domaine (DOM_ID_N,DOM_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (2,'Outils','wwra@wyniwyg.fr','2006-01-10-00.00.00','2006-01-10',null);
INSERT INTO t_domaine (DOM_ID_N,DOM_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (3,'Gestion de Projet','wwra@wyniwyg.fr','2006-01-10-00.00.00',null,null);




INSERT INTO t_rubrique_type (RBT_ID_N,RBT_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (1,'Formation','gestcv.sourceforge.net','2006-01-12-00.00.00',null,null);
INSERT INTO t_rubrique_type (RBT_ID_N,RBT_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (2,'Expérience','gestcv.sourceforge.net','2006-01-12-00.00.00',null,null);
INSERT INTO t_rubrique_type (RBT_ID_N,RBT_NOM_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION) VALUES (3,'Compétence','gestcv.sourceforge.net','2006-01-12-00.00.00',null,null);




INSERT INTO t_rubrique (RUB_ID_N,RUB_DESCRIPTION_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION,RUB_ID_TYPE_N) VALUES (1,'vbfbbgbgvsdvvf','gestcv.sourceforge.net','2006-01-12-00.00.00',null,null,3);
INSERT INTO t_rubrique (RUB_ID_N,RUB_DESCRIPTION_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION,RUB_ID_TYPE_N) VALUES (2,null,'gestcv.sourceforge.net','2006-01-13-00.00.00',null,null,3);
INSERT INTO t_rubrique (RUB_ID_N,RUB_DESCRIPTION_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION,RUB_ID_TYPE_N) VALUES (3,null,'gestcv.sourceforge.net','2006-01-13-00.00.00',null,null,3);
INSERT INTO t_rubrique (RUB_ID_N,RUB_DESCRIPTION_C,UTILISATEUR_CREATION,DATE_CREATION,UTILISATEUR_MODIFICATION,DATE_MODIFICATION,RUB_ID_TYPE_N) VALUES (4,'Test formation ','gestcv.sourceforge.net','2006-05-10-00.00.00',null,null,1);
