INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('angelo (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('djo (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('keulkeul (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('pascal (H2)', '');