INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('Angelo ZERR (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('Martin Lippert (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('Pascal Leclercq (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('Jawher Moussa (H2)', '');
INSERT INTO T_USER (USR_LOGIN_C, USR_PASSWORD_C) VALUES ('Mickael BARON (H2)', '');
